.\" Manpage for lidm
.\" https://github.com/javalsai/lidm
.TH lidm 1

.SH NAME
lidm \- A text based display manager made in C


.SH SYNOPSIS
\fBlidm\fP [TTY]


.SH DESCRIPTION
\fBlidm\fP is a text based display manager that supports a lot of configuration. Its focus is to be simple, minimal and easy to compile even on really old hardware, while being as customizable as possible.


.SH ARGUMENTS
.TP
\fB[TTY]\fP
TTY to switch to, does not mean that it will run in it.

.SH ENVIRONMENT
.TP
\fBLIDM_CONF\fP
Specify the config to use other than \fI/etc/lidm.ini\fP
.TP
\fBLIDM_LOG\fP
Optionally, a path to output misc logs and potential silent failures.

.SH FILES
.TP
\fI/etc/lidm.ini\fP
Config file, see
.BR lidm-config (5)
for syntax.


.SH NOTES
.SS "Service Files"
To configure startup behaviour for your init system, see
.BR https://github.com/javalsai/lidm/tree/master/assets/services
(make sure you're on the same version, the link points to the latest commit, small command arguments might have changed).


.SH "SEE ALSO"
.BR lidm-config (5)
.PP
The upstream GitHub repository can be found at
.BR https://github.com/javalsai/lidm
